import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useAnimeListQuery } from '../src/graphql/anime-list';

export default function Home() {
  const { data, isLoading } = useAnimeListQuery({
    page: 1,
    perPage: 9
  });
  console.log({ isLoading, data });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
